// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("grpccheck")
	ScopeName = "bou.ke/grpccheckreceiver"
)

const (
	MetricsStability = component.StabilityLevelAlpha
)
